export const TEST_DATA_GET_USER_COHORT = {
  id: 1,
  cohortName: 'Software Development, Cohort 69',
  people: [
    {
      id: 1,
      bio: 'Full-stack developer passionate about clean code and scalable apps.',
      email: 'alice.johnson@example.com',
      endDate: '2025-06-30',
      firstName: 'Alice',
      githubUrl: 'https://github.com/alicejohnson',
      lastName: 'Johnson',
      mobile: '+15551234567',
      photo: 'https://randomuser.me/api/portraits/women/1.jpg',
      role: 0,
      specialism: 'Full Stack',
      startDate: '2025-01-15',
      username: 'alicej'
    },
    {
      id: 2,
      bio: 'Frontend specialist who loves building engaging UIs with React.',
      email: 'brandon.smith@example.com',
      endDate: '2025-06-30',
      firstName: 'Brandon',
      githubUrl: 'https://github.com/brandonsmith',
      lastName: 'Smith',
      mobile: '+15557654321',
      photo: 'https://randomuser.me/api/portraits/men/2.jpg',
      role: 0,
      specialism: 'Frontend',
      startDate: '2025-01-15',
      username: 'brandon_s'
    },
    {
      id: 3,
      bio: 'Backend engineer interested in cloud infrastructure and APIs.',
      email: 'carla.lee@example.com',
      endDate: '2025-06-30',
      firstName: 'Carla',
      githubUrl: 'https://github.com/carlalee',
      lastName: 'Lee',
      mobile: '+15559876543',
      photo: 'https://randomuser.me/api/portraits/women/3.jpg',
      role: 0,
      specialism: 'Backend',
      startDate: '2025-01-15',
      username: 'carla_lee'
    },
    {
      id: 4,
      bio: 'Data scientist with a focus on machine learning and analytics.',
      email: 'david.khan@example.com',
      endDate: '2025-06-30',
      firstName: 'David',
      githubUrl: 'https://github.com/davidkhan',
      lastName: 'Khan',
      mobile: '+15553456789',
      photo: 'https://randomuser.me/api/portraits/men/4.jpg',
      role: 0,
      specialism: 'Data Science',
      startDate: '2025-01-15',
      username: 'davidk'
    },
    {
      id: 5,
      bio: 'UX designer turned developer, passionate about accessibility.',
      email: 'emily.roberts@example.com',
      endDate: '2025-06-30',
      firstName: 'Emily',
      githubUrl: 'https://github.com/emilyroberts',
      lastName: 'Roberts',
      mobile: '+15554329876',
      photo: 'https://randomuser.me/api/portraits/women/5.jpg',
      role: 0,
      specialism: 'UX / Frontend',
      startDate: '2025-01-15',
      username: 'emilyr'
    }
  ]
};
